### PR TITLE
I'd Create An Issue But..

### PR DESCRIPTION
**Pull request by HopperMCS**
Hello, James:

I was gonna create an issue but you've disabled them. I'm going to create my own template for issues etc. But anyway, I did contact you, now I'm contacting you here as well as your e-mail. 

I have interest developing an extension for Monaco, specifically. It seems you've done work in the backend. 

Please check the e-mail account you have associated with your GitHub.

### CODE REVIEW

**Comment by HopperMCS** [comment]
Just on a sidenote, I did not mean to do this here. But, however, if Mr. Friesen is in fact out there, y u no use skills?

**Comment by dantman** [comment]
You're probably better off updating the Skin:Monaco page to point to other forks.

Judging by the date of the first commit and the fact GitHub is telling me there are merge conflicts, your pull request isn't even based on the latest version of my old code. It's based on another fork that already diverged and never incorporated changes made after April.

Even if I were to review and accept pull requests to this old project I'm no longer really using; there are a number of changes here I just can't merge in:
- Removal of the alt skin
- Hardcoded images embedded from your wiki and Wikia, images embedded from a hardcoded /skins/ path, and hardcoded links to your wiki
- `include "monaco.php";` in the middle of a PHP file, bad PHP on so many levels
- English text hardcoded into skin files with no i18n handling
- References to `$wgUser` used in multiple ways it should not be used
- New "features" not every user wants or needs hardcoded into the skin instead of implemented as pluggable extensions
- Concatenating HTML with variables in JavaScript

Side note, wfMessage is also incorrect you're supposed to use `->msg` on the nearest context object, in this case the Skin subclass or the BaseTemplate if something was added to it. Also you shouldn't be using $wgLang either.

**Comment by HopperMCS** [comment]
I meant to post it on the other fork, but hey thanks for replying (I can't seems to get anything from James, lol and yes there are merge conflicts. GH tripped out on me and I meant to rescind this merge but it was too late)

**Comment by HopperMCS** [comment]
And yup, read the README dantman, because Mission Control isn't going anywhere, I'm actually stubborn about that one.

**Comment by msnhinet8** [comment]
Hi, how can i install monaco skin in my wiki?

**Comment by HopperMCS** [comment]
@dantman quit maintaining this a loooong time ago. I had a fork but haven't maintained it since last year lmao. Actually been working with others on newer projects...

**Pull request closed without merging**
